runtime: python39
service: beta

handlers:
  - url: /static
    static_dir: frontend/static/

  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

includes:
  - secrets.yaml
