# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lake_bottom_web', '0002_show_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='user',
        ),
    ]
