# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0004_auto_20170613_1952"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="playlist_file",
            field=models.FileField(null=True, upload_to="playlists"),
        ),
        migrations.AlterField(
            model_name="show",
            name="published",
            field=models.BooleanField(default=True),
        ),
    ]
