# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0011_live_stream_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1027)),
                ("artist", models.CharField(max_length=1027)),
                ("album", models.CharField(max_length=1027)),
                ("year", models.CharField(max_length=1027)),
            ],
        ),
        migrations.AddField(
            model_name="show",
            name="songs",
            field=models.ManyToManyField(to="lake_bottom_web.Song"),
        ),
    ]
