# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0012_auto_20190818_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="playlist_field",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
