# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake_bottom_web', '0013_show_playlist_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='playlist_file',
            field=models.FileField(null=True, upload_to='/tmp'),
        ),
    ]
