# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-21 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake_bottom_web', '0017_show_show_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default=None, max_length=1027),
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
