# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-08-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0018_auto_20190821_2225"),
    ]

    operations = [
        migrations.AddField(
            model_name="live",
            name="heading",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="live",
            name="subheading",
            field=models.CharField(default="", max_length=255),
        ),
    ]
