# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-02-18 16:02
from __future__ import unicode_literals

from django.db import migrations


def create_through_relations(apps, schema_editor):
    Show = apps.get_model("lake_bottom_web", "Show")
    ShowSongs = apps.get_model("lake_bottom_web", "ShowSongs")

    for show in Show.objects.all():
        order = 0
        for song in show.songs.all():
            ShowSongs(show=show, song=song, order=order).save()
            order += 1


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0020_auto_20200218_1515"),
    ]

    operations = [
        migrations.RunPython(
            create_through_relations, reverse_code=migrations.RunPython.noop
        ),
    ]
