# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-02-18 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lake_bottom_web", "0021_auto_20200218_1602"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="songs",
        ),
    ]
