# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2020-02-18 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake_bottom_web', '0022_remove_show_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='songs',
            field=models.ManyToManyField(through='lake_bottom_web.ShowSongs', to='lake_bottom_web.Song'),
        ),
    ]
